env:
  node: true
extends: 'plugin:vue/recommended' #'eslint:recommended'
parserOptions:
  ecmaVersion: 2017
rules:
  indent:
    - warn
    - tab
  linebreak-style:
    - warn
    - windows
  quotes:
    - warn
    - double
  semi:
    - warn
    - always
