service: serverlesstest3 # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-2
  # deploymentBucket: aws-codestar-us-east-2-672998989107-serverlesstest-pipe

package:
  exclude:
    - node_modules/**

functions:
  main:
    handler: handler.main
    events:
      - http: ANY {proxy+}

plugins:
  - serverless-apigw-binary
  - serverless-offline
  - serverless-sam
 
custom:
  apigwBinary:
    types:
      - '*/*'

# Use: `serverless config credentials --provider aws --key --secret` to setup aws credentials
# Current credentials: `serverless config credentials --provider aws --key  AKIAI2QTJDWA62I VDPYA --secret 3Ccz7evfjeIFPdIS+JqkPRt6qFJxLwsighXGfb86`