AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'SAM template for Serverless framework service: '
Resources:
  Main:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.main
      Runtime: nodejs8.10
      CodeUri: >-
        C:\Users\rol4400\Documents\Repos\ServerlessTest\.serverless\serverlesstest3.zip
      MemorySize: 128
      Timeout: 3
      Events:
        Event1:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: ANY
            RestApiId:
              Ref: Serverlesstest3
  Serverlesstest3:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: dev
      DefinitionBody:
        swagger: '2.0'
        info:
          title:
            Ref: 'AWS::StackName'
        paths:
          '/{proxy+}':
            any:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  'Fn::Sub': >-
                    arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Main.Arn}/invocations
              responses: {}
  MainLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    DependsOn:
      - Main
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        Ref: Main
      Principal: apigateway.amazonaws.com
